---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: majdiguedri
    password: 4336c36d-298c-4bde-8d76-d6f031ce13e8

- name: Tag and push to docker hub
  docker_image:
    name: devops:latest
    repository: majdiguedri/cd_project
    tag: end
    push: yes
